title: Tutorials zur Vorlesung Algorithmen
author: Jan Christiansen
email: jan.christiansen@hs-flensburg.de
description: >
  Hochschule Flensburg / Fachbereich 3 Information und Kommunikation / Angewandte Informatik

minima:
  date_format: "%d. %b %Y"

theme: minima