title: Tutorials zur Vorlesung Algorithmen
author: Jan Christianse
email: jan.christiansen@hs-flensburg.de
description: >
  Tutorials zur Verwendung von Eclipse und git bzw. GitHub für die Vorlesung Algorithmen.

minima:
  date_format: "%d. %b %Y"

theme: minima